name: ci

on: [push, pull_request]

jobs:
  build:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Pkgs
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        env:
          JEST_FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
        run: yarn test
